# Generated by Django 2.2 on 2020-02-27 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Cousin', 'Cousin'), ('Grand-Parent', 'Grand-Parent'), ('Other', 'Other')], max_length=200, verbose_name='Relation')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
        ),
    ]
