# Generated by Django 2.2 on 2020-01-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_user_is_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fees',
            options={'verbose_name': 'Fee Structure', 'verbose_name_plural': 'Fees Structure'},
        ),
        migrations.RemoveField(
            model_name='parent',
            name='student',
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ManyToManyField(to='school.Student'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to="users/pictures/%Y/%m/%d'"),
        ),
    ]
