# Generated by Django 2.2 on 2020-01-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200113_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseUnit',
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='school.Level', verbose_name='Grade'),
        ),
    ]
