# Generated by Django 2.2 on 2020-01-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200116_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pupilattendance',
            name='attended',
        ),
        migrations.AddField(
            model_name='pupilattendance',
            name='mark_attendance',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=50),
        ),
    ]
